esphome:
  name: electriq-12000-ac
  includes:
    - electriq_ac.h

esp8266:
  board: esp01_1m

# Enable logging (and disable DEBUG)
logger:
  level: INFO

# Enable Home Assistant API
api:

ota:
  password: "SET_BY_HOME_ASSISTANT"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Electriq-12000-Ac-1"
    password: "SET_BY_HOME_ASSISTANT"

captive_portal:

uart:
  id: uart_bus
  rx_pin: GPIO13
  tx_pin: GPIO15
  baud_rate: 9600

climate:
  - platform: custom
    lambda: |-
      auto electriqac = new ElectriqAC(id(uart_bus));
      App.register_component(electriqac);
      return {electriqac};
    climates:
      - name: "Electriq 12000 AC 1"
# overrun automation below here. This is optional but recommended.
        on_state:
          - delay: 2s
          - if:
              condition:
                lambda: 'return ((id(electriqac).action == CLIMATE_ACTION_IDLE) && (id(electriqac).mode == CLIMATE_MODE_HEAT) && !id(overrun));'
              then:
                - globals.set:
                    id: 'overrun'
                    value: 'true'
                - logger.log: "Overrun fan mode, waiting 30s"
                - climate.control:
                    id: 'electriqac'
                    mode: FAN_ONLY
                - delay: 30s
                - if:
                    condition:
                      lambda: 'return (id(electriqac).action == CLIMATE_ACTION_FAN);'
                    then:
                      - logger.log: "Overrun finished, reverting to heat mode"
                      - climate.control:
                          id: 'electriqac'
                          mode: HEAT
          - if:
              condition:
                lambda: 'return ((id(electriqac).action == CLIMATE_ACTION_HEATING) && id(overrun));'
              then:
               - logger.log: "Resetting overrun"
               - globals.set:
                    id: 'overrun'
                    value: 'false'
                    
globals:
  - id: overrun
    type: bool
    initial_value: 'true'
